meta_product_name: "Happy Tails"
meta_title: "Happy Tails - Find your local Happy Tail"
meta_description: "The goodest way to get those tails waggin'"
meta_image: "logo_gradient.png" # should exist in `app/assets/images/`
