meta_product_name: "Happy Tails"
meta_title: "Happy Tails - Find your local happy tail"
meta_description: "Relevant description"
meta_image: "logo_gradient.png" # should exist in `app/assets/images/`
